### ISSUE TITLE
Tests for WebFetch-Input-RSS-0.2.1 have started to fail with WebFetch-0.15.4

### ISSUE THREAD

**Issue by andk** [ikluft/WebFetch#4]
As per subject. Two test reports with a random perl before and after the upgrade of WebFetch:

- before (pass): http://www.cpantesters.org/cpan/report/e970caa2-549a-11ed-8a65-198266ca80ec
- after (fail): http://www.cpantesters.org/cpan/report/935802f2-549f-11ed-ad30-9fb066ca80ec

**Comment by ikluft** [comment]
This should be resolved. But I'll watch for the results from CPAN Testers first. I was in the process of reorganizing WebFetch::Input::RSS and renaming it to WebFetch::RSS, because it isn't just input any more. So look for the change there. The renamed module does still contain a WebFetch::Input::RSS for backward compatibility, which does nothing more than inherit everything from WebFetch::RSS as its parent class. The unit tests were modified to perform each test on both old and new class names.
